Library-Management-System/Models/AuthorViewModel.cs
namespace Library_Management_System.Models
{
    public class AuthorViewModel
    {
        public int Id { get; set; } 

        public string FirstName { get; set; }  

        public string LastName { get; set; }  

        public DateTime DateOfBirth { get; set; }

        

    }
}

Library-Management-System/Controllers/AuthorController.cs
using Library_Management_System.Entities;
using Microsoft.AspNetCore.Mvc;
using Library_Management_System.Models;


namespace Library_Management_System.Controllers
{
    public class AuthorController : Controller
    {

        static List<AuthorEntity> _authors = new List<AuthorEntity>()
        {
           
        new AuthorEntity{Id = 1, FirstName = "Omer", LastName = "Seyfettin", DateOfBirth = new DateTime(1884, 03, 11, 0, 0, 0)},
      new AuthorEntity{Id = 2, FirstName = "Resat Nuri", LastName= " Guntekin", DateOfBirth = new DateTime(1889, 11, 25, 0, 0, 0)},
      new AuthorEntity{Id = 3, FirstName = "Paulo", LastName= "Coelho", DateOfBirth = new DateTime(1947, 08, 24, 0, 0, 0)}
         };


        // List of authors

        public IActionResult AuthorList()
        {
            var viewModel = _authors.Where(x => x.IsDeleted == false).Select(x => new AuthorViewModel
            {

                Id = x.Id,
                FirstName = x.FirstName,
                LastName = x.LastName,
                DateOfBirth = x.DateOfBirth
            }).ToList();

            return View(viewModel);
        }


        // Creating a new Author

        [HttpGet]
        public IActionResult AuthorCreate()
        {
            ViewBag.Authors = _authors;

            return View();
        }


        [HttpPost]
        public IActionResult AuthorCreate(AuthorViewModel formData)
        {

            if (!ModelState.IsValid)
            {
                return View(formData);
            }

            int maxId = _authors.Max(x => x.Id);

            var newAuthor = new AuthorEntity()
            {
                Id = maxId + 1,
                FirstName = formData.FirstName,
                LastName = formData.LastName,
                DateOfBirth = formData.DateOfBirth


            };
            _authors.Add(newAuthor);

            return RedirectToAction("AuthorList");
        }

        // Updating author information

        [HttpGet]
        public IActionResult AuthorEdit(int id)
        {
            var author = _authors.Find(x => x.Id == id);

            var viewModel = new AuthorViewModel()
            {
                Id = author.Id,
                FirstName = author.FirstName,
                LastName = author.LastName,
                DateOfBirth = author.DateOfBirth

            };

            ViewBag.Authors = _authors;

            return View(viewModel);
        }


        [HttpPost]
        public IActionResult AuthorEdit(AuthorViewModel formData)
        {
            if (!ModelState.IsValid)
            {
                return View(formData);
            }

            var author = _authors.Find(x => x.Id == formData.Id);

            author.FirstName = formData.FirstName;
            author.LastName = formData.LastName;
            author.DateOfBirth = formData.DateOfBirth;


            return RedirectToAction("AuthorList");
        }


        // Display author information

        public IActionResult AuthorDetail(int id)
        {
            var author = _authors.Find(x => x.Id == id);

            var viewModel = new AuthorViewModel
            {
                Id = author.Id,
                FirstName = author.FirstName,
                LastName = author.LastName,
                DateOfBirth = author.DateOfBirth,

            };

            return View(viewModel);

        }

        // Author deletion

        public IActionResult AuthorDelete(int id)
        {
            var author = _authors.Find(x => x.Id == id);

            author.IsDeleted = true;

            return RedirectToAction("AuthorList");
        }

    }

}

Library-Management-System/Views/Author/AuthorCreate.cshtml
@model AuthorViewModel


<h1 class="text-center mt-5">Yeni Yazar Ekle</h1>

<form method="post" asp-controller="Author" asp-action="AuthorCreate">

    <div>
        <label>Yazar Adı</label>
        <input asp-for="FirstName" class="form-control" type="text" />
        <span asp-validation-for="FirstName" class=" text-danger mt-2 fw-bold"></span>
        
    </div>

    <div>
        <label>Yazar Soyadı</label>
        <input asp-for="LastName" class="form-control" type="text" />
        <span asp-validation-for="LastName" class=" text-danger mt-2 fw-bold"></span>
    </div>

    <div>

        <label>Doğum Tarihi</label>
        <input asp-for="DateOfBirth" class="form-control" type="date" />
        <span asp-validation-for="DateOfBirth" class=" text-danger mt-2 fw-bold"></span>
    </div>

    <button type="submit" class="btn btn-success mt-2">Kaydet</button>
</form>

Library-Management-System/Views/Author/AuthorDetail.cshtml
@model AuthorViewModel


<h1 class="text-center mt-5">Yazar Bilgileri</h1>
<input type="hidden" asp-for="Id" />

<div class="mt-5">
<table class="table">
    <thead>
        <tr>
            <th>ADI</th>
            <th>SOYADI</th>
            <th>DOĞUM TARİHİ</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>@Model.FirstName</td>
            <td>@Model.LastName</td>
            <td>@Model.DateOfBirth.ToString("dd/MM/yyyy")</td>
        </tr>
    </tbody>
</table>
</div>

Library-Management-System/Views/Author/AuthorEdit.cshtml
@model AuthorViewModel

<h1 class="text-center mt-5">Yazar Bilgileri Düzenle</h1>

<form method="post" asp-controller="Author" asp-action="AuthorEdit">

    <input type="hidden" asp-for="Id" />

  
    <div>
        <label>Yazar Adı</label>
        <input asp-for="FirstName" class="form-control" type="text" />
        <span asp-validation-for="FirstName" class=" text-danger mt-2 fw-bold"></span>
    </div>

    <div>
        <label>Yazar Soyadı</label>
        <input asp-for="LastName" class="form-control" type="text" />
        <span asp-validation-for="LastName" class=" text-danger mt-2 fw-bold"></span>
    </div>

    <div>

        <label>Doğum Tarihi</label>
        <input asp-for="DateOfBirth" class="form-control" type="date" />
        <span asp-validation-for="DateOfBirth" class=" text-danger mt-2 fw-bold"></span>
    </div>

    <button type="submit" class="btn btn-success mt-2">Kaydet</button>
</form>

Library-Management-System/Views/Author/AuthorList.cshtml
@model List<AuthorViewModel>
<div class="alert alert-info fw-bold">

       Hos Geldin - @User.Claims.FirstOrDefault( x =>x.Type == "email")?.Value
        @User.Claims.FirstOrDefault( x =>x.Type == "id")?.Value
        
    </div>

    @if(@User.Claims.FirstOrDefault(x => x.Type == "id")?.Value is not null)
    {

    <h1 class="text-center mt-5">YAZARLAR</h1>

    <a asp-controller="Author" asp-action="AuthorCreate" class="btn btn-success fw-bold mb-3 mt-3">Yeni Yazar Ekle</a>

    <div class="mt-5">

        @foreach (var author in Model)
    {
        <div class="card">
            
            <div class="card-body">
                
                <p class="card-text">Yazar Adı: @author.FirstName</p>
                <p class="card-text">Yazar Soyadı: @author.LastName</p>
                
                <a asp-controller="Author" asp-action="AuthorEdit" asp-route-id="@author.Id" class="btn btn-primary">Düzenle</a>          
                <a asp-controller="Author" asp-action="AuthorDetail" asp-route-id="@author.Id" class="btn btn-warning">Ayrıntılar</a>
                    <a asp-controller="Author" asp-action="AuthorDelete" asp-route-id="@author.Id" class="btn btn-danger">Sil</a>
            </div>
        </div>
    }

    </div>

}